# Generated by Django 5.0.1 on 2025-08-02 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
