# Generated by Django 5.0.1 on 2025-08-03 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_call_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='report',
            field=models.TextField(blank=True, null=True),
        ),
    ]
